# Generated by Django 4.1.5 on 2023-02-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='brand',
            field=models.CharField(default='', max_length=255),
        ),
    ]
