# Generated by Django 4.1.5 on 2023-02-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_produit_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='produit',
            name='promotion',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=6),
        ),
    ]
