# Generated by Django 4.1.5 on 2023-02-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_produit_frais_livraison_alter_produit_prix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='frais_livraison',
        ),
        migrations.AddField(
            model_name='produit',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
