# Generated by Django 4.1.5 on 2023-02-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_remove_produit_frais_livraison_produit_free_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='free',
            new_name='liv',
        ),
    ]
