# Generated by Django 4.1.5 on 2023-02-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0006_rename_liv_produit_livraison_gratuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='etoiles',
            field=models.ImageField(default=5, max_length=2, upload_to=''),
        ),
    ]
