# Generated by Django 4.1.5 on 2023-02-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0007_produit_etoiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='etoiles',
            field=models.IntegerField(default=5, max_length=1),
        ),
    ]
