# Generated by Django 4.1.5 on 2023-02-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produit', '0003_produit_frais_livraison_alter_produit_prix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('wilaya', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('crée_le', models.DateTimeField(auto_now_add=True)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'ordering': ['-crée_le'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantité', models.IntegerField(default=1)),
                ('nom_produit', models.CharField(default='', max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='commande.commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='produit.produit')),
            ],
        ),
    ]
