# Generated by Django 4.1.5 on 2023-02-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecommande',
            old_name='order',
            new_name='commande',
        ),
        migrations.RenameField(
            model_name='articlecommande',
            old_name='product',
            new_name='produit',
        ),
        migrations.AlterField(
            model_name='articlecommande',
            name='quantité',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
