# Generated by Django 4.1.5 on 2023-02-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_rename_order_articlecommande_commande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecommande',
            name='quantité',
        ),
        migrations.AddField(
            model_name='articlecommande',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
